---
# handlers file for apache

- name: restart apache
  service:
    name: httpd
    state: restarted
  become: true

- name: restart httpd
  service:
    name: httpd
    state: restarted
  become: true