---
# Ansible tasks for apache-webapp role

- name: "Start Apache Web Sever Install and configuration"
  debug:
    msg: "Launch {{ webapp_name }} Apache Web Sever Install and configuration {{ ansible_hostname }}"
  
- name: "Install Apache web server packages"
  package:
    name: apache2    
    update_cache: yes
    state: latest

- name: "Create document root direcotry"
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: "Copy webapp files to server"
  template:
    src: "{{ item }}"
    dest: "/var/www/{{ http_host }}/{{ item | basename }}" 
    mode: '0755'
  with_fileglob:
    - "../files/app/*"

- name: "Configure Apache virtual host"
  template:
    src: templates/vhost.conf.j2
    dest: /etc/apache2/sites-available/webapp.conf
  notify: Restart Apache

- name: "UFW firewall allow HTTP on port {{ http_port }}"
  ufw:
    rule: allow
    port: "{{ http_port }}"
    protocol: tcp

- name: "Enable Apache virtual host"
  apache2_module:
    state: present
    name: vhost_alias

- name: "Enable site"
  command: a2ensite webapp.conf
  args:
    creates: /etc/apache2/sites-enabled/webapp.conf
  register: enable_site
  notify: Restart Apache
  
- name: Ensure Apache server is running
  service:
    name: apache2
  register: apache_service_status

- debug:
    msg: "{{ apache_service_status }}"
    
- name: "End Apache Web App deployement"
  debug:
    msg: "{{ webapp_name }} is deployed successfully"
  when: (enable_site.rc == 0) and (apache_service_status.state == "running")

...
