---
# Ansible tasks for apache-webapp role

- name: "Start Apache Web Sever Install and configuration"
  debug:
    msg: "Launch {{ webapp_name }} Apache Web Sever Install and configuration {{ ansible_hostname }}"
  
- name: "Install Apache web server packages"
  package:
    name: apache2    
    update_cache: yes
    state: latest

- name: "Create document root direcotry"
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: "Copy webapp files to server"
  template:
    src: "{{ item }}"
    dest: "/var/www/{{ http_host }}/{{ item | basename }}" 
    mode: '0755'
  with_fileglob:
    - "../files/*"

- name: "Set up VirtualHost"
  template:
    src: "apache2.conf.j2"
    dest: "/etc/apache2/sites-available/apache2.conf"

- name: "UFW firewall allow HTTP on port {{ http_port }}"
  ufw:
    rule: allow
    port: "{{ http_port }}"
    protocol: tcp

- name: "Enable {{ http_host }} site"
  command: a2ensite {{ http_host }}
  register: enable_site
  notify: restart-apache
  ignore_errors: yes
  
- name: "End Apache Web App deployement"
  debug:
    msg: "{{ webapp_name }} is deployed successfully"
  # when: enable_site.rc == "0"

...
